- name: Baixando Repositorio CentOS
  get_url:
    url: https://yum.puppet.com/puppet6/puppet6-release-el-5.noarch.rpm
    dest: /root/

- name: Baixando Repositorio Debian
  get_url:
    url: https://apt.puppetlabs.com/puppet6-release-xenial.deb
    dest: /root/

